version: "2"

services:
  default:
    build: .
    container_name: last_vocabulary_bot
    entrypoint:
     - python
     - -u
     - main.py
    env_file:
      - .env
  pyconsole:
    build: .
    container_name: last_vocabulary_bot_pyconsole
    entrypoint:
     - python
    tty: true
    stdin_open: true
    env_file:
      - .env     
  shconsole:
    build: .
    container_name: last_vocabulary_bot_shconsole
    entrypoint:
     - sh
    tty: true
    stdin_open: true
    env_file:
      - .env
